In [4]:
import numpy as np

x = np.random.rand(10, 5)
permutation = np.random.permutation(x.shape[0])
permutation

array([7, 6, 4, 5, 8, 0, 1, 2, 3, 9])

In [5]:
x

array([[0.4279338 , 0.01297655, 0.44557714, 0.59174962, 0.90641223],
       [0.43773207, 0.83380175, 0.99522367, 0.22534507, 0.8802737 ],
       [0.05863936, 0.88791694, 0.70680151, 0.95287154, 0.99565883],
       [0.18205636, 0.95054955, 0.3139508 , 0.68154571, 0.21398151],
       [0.85709981, 0.51874216, 0.49262266, 0.75381727, 0.91383737],
       [0.54150468, 0.16145779, 0.00241058, 0.28692056, 0.03604999],
       [0.88468345, 0.51179651, 0.81053798, 0.82963712, 0.4992116 ],
       [0.63250463, 0.74122957, 0.45535352, 0.98906976, 0.92566147],
       [0.0736217 , 0.55578217, 0.8837303 , 0.31209498, 0.96895527],
       [0.05570436, 0.72954941, 0.294924  , 0.46055959, 0.40286508]])

In [6]:
x = x[permutation, :] # 데이터(row) 뒤섞기
x

array([[0.63250463, 0.74122957, 0.45535352, 0.98906976, 0.92566147],
       [0.88468345, 0.51179651, 0.81053798, 0.82963712, 0.4992116 ],
       [0.85709981, 0.51874216, 0.49262266, 0.75381727, 0.91383737],
       [0.54150468, 0.16145779, 0.00241058, 0.28692056, 0.03604999],
       [0.0736217 , 0.55578217, 0.8837303 , 0.31209498, 0.96895527],
       [0.4279338 , 0.01297655, 0.44557714, 0.59174962, 0.90641223],
       [0.43773207, 0.83380175, 0.99522367, 0.22534507, 0.8802737 ],
       [0.05863936, 0.88791694, 0.70680151, 0.95287154, 0.99565883],
       [0.18205636, 0.95054955, 0.3139508 , 0.68154571, 0.21398151],
       [0.05570436, 0.72954941, 0.294924  , 0.46055959, 0.40286508]])

In [8]:
batch_mask = np.random.choice(20, 10)
batch_mask

array([13, 19,  9, 15, 11, 11,  5, 16,  6,  0])